//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace MCSApp.WSProductTrace {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductTraceSoap", Namespace="http://tempuri.org/")]
    public partial class ProductTrace : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetModelIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSNOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlanIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveComponentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProductTrace() {
            this.Url = global::MCSApp.Properties.Settings.Default.MCSApp_WSProductTrace_ProductTrace;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetModelIDCompletedEventHandler GetModelIDCompleted;
        
        /// <remarks/>
        public event GetSNCompletedEventHandler GetSNCompleted;
        
        /// <remarks/>
        public event GetPlanIDCompletedEventHandler GetPlanIDCompleted;
        
        /// <remarks/>
        public event SaveProductCompletedEventHandler SaveProductCompleted;
        
        /// <remarks/>
        public event SaveComponentCompletedEventHandler SaveComponentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetModelID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetModelID(string BarCode, out string oMsg) {
            object[] results = this.Invoke("GetModelID", new object[] {
                        BarCode});
            oMsg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetModelIDAsync(string BarCode) {
            this.GetModelIDAsync(BarCode, null);
        }
        
        /// <remarks/>
        public void GetModelIDAsync(string BarCode, object userState) {
            if ((this.GetModelIDOperationCompleted == null)) {
                this.GetModelIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModelIDOperationCompleted);
            }
            this.InvokeAsync("GetModelID", new object[] {
                        BarCode}, this.GetModelIDOperationCompleted, userState);
        }
        
        private void OnGetModelIDOperationCompleted(object arg) {
            if ((this.GetModelIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModelIDCompleted(this, new GetModelIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSN(string BarCode, out string oMsg) {
            object[] results = this.Invoke("GetSN", new object[] {
                        BarCode});
            oMsg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSNAsync(string BarCode) {
            this.GetSNAsync(BarCode, null);
        }
        
        /// <remarks/>
        public void GetSNAsync(string BarCode, object userState) {
            if ((this.GetSNOperationCompleted == null)) {
                this.GetSNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSNOperationCompleted);
            }
            this.InvokeAsync("GetSN", new object[] {
                        BarCode}, this.GetSNOperationCompleted, userState);
        }
        
        private void OnGetSNOperationCompleted(object arg) {
            if ((this.GetSNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSNCompleted(this, new GetSNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPlanID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPlanID(string BarCode, out string oMsg) {
            object[] results = this.Invoke("GetPlanID", new object[] {
                        BarCode});
            oMsg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlanIDAsync(string BarCode) {
            this.GetPlanIDAsync(BarCode, null);
        }
        
        /// <remarks/>
        public void GetPlanIDAsync(string BarCode, object userState) {
            if ((this.GetPlanIDOperationCompleted == null)) {
                this.GetPlanIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlanIDOperationCompleted);
            }
            this.InvokeAsync("GetPlanID", new object[] {
                        BarCode}, this.GetPlanIDOperationCompleted, userState);
        }
        
        private void OnGetPlanIDOperationCompleted(object arg) {
            if ((this.GetPlanIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlanIDCompleted(this, new GetPlanIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveProduct(string PlanID, string UID, string ID, string ModelID, string Remark, out string oMsg) {
            object[] results = this.Invoke("SaveProduct", new object[] {
                        PlanID,
                        UID,
                        ID,
                        ModelID,
                        Remark});
            oMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveProductAsync(string PlanID, string UID, string ID, string ModelID, string Remark) {
            this.SaveProductAsync(PlanID, UID, ID, ModelID, Remark, null);
        }
        
        /// <remarks/>
        public void SaveProductAsync(string PlanID, string UID, string ID, string ModelID, string Remark, object userState) {
            if ((this.SaveProductOperationCompleted == null)) {
                this.SaveProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveProductOperationCompleted);
            }
            this.InvokeAsync("SaveProduct", new object[] {
                        PlanID,
                        UID,
                        ID,
                        ModelID,
                        Remark}, this.SaveProductOperationCompleted, userState);
        }
        
        private void OnSaveProductOperationCompleted(object arg) {
            if ((this.SaveProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveProductCompleted(this, new SaveProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveComponent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveComponent(string PlanID, string UID, string ID, string ModelID, string Remark, out string oMsg) {
            object[] results = this.Invoke("SaveComponent", new object[] {
                        PlanID,
                        UID,
                        ID,
                        ModelID,
                        Remark});
            oMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SaveComponentAsync(string PlanID, string UID, string ID, string ModelID, string Remark) {
            this.SaveComponentAsync(PlanID, UID, ID, ModelID, Remark, null);
        }
        
        /// <remarks/>
        public void SaveComponentAsync(string PlanID, string UID, string ID, string ModelID, string Remark, object userState) {
            if ((this.SaveComponentOperationCompleted == null)) {
                this.SaveComponentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveComponentOperationCompleted);
            }
            this.InvokeAsync("SaveComponent", new object[] {
                        PlanID,
                        UID,
                        ID,
                        ModelID,
                        Remark}, this.SaveComponentOperationCompleted, userState);
        }
        
        private void OnSaveComponentOperationCompleted(object arg) {
            if ((this.SaveComponentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveComponentCompleted(this, new SaveComponentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetModelIDCompletedEventHandler(object sender, GetModelIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModelIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModelIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string oMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSNCompletedEventHandler(object sender, GetSNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string oMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPlanIDCompletedEventHandler(object sender, GetPlanIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlanIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlanIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string oMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveProductCompletedEventHandler(object sender, SaveProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string oMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SaveComponentCompletedEventHandler(object sender, SaveComponentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveComponentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveComponentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string oMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591